# Generated by Django 4.2.7 on 2025-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
