# Generated by Django 4.2.7 on 2025-09-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_qrcode_qr_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='hls_url',
            field=models.URLField(blank=True),
        ),
    ]
