# Generated by Django 4.2.7 on 2025-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mediaasset_hls_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
